services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: true

north:
  jupyterhub_crypt_key: ''
  enabled: true
  tools:
    include:
      - voila
      - jupyter2
    options:
      jupyter2:
        short_description: A jupyter webapp container with voila opens notebook
        description: A jupyter hub webapp container with voila installed.
        image: ghcr.io/nomad-hzb/perotf-image/jupyter:main
        path_prefix: lab/tree
        with_path: true
        mount_path: /home/jovyan
        file_extensions:
          - ipynb
        maintainer:
          - name: Michael Götte
            email: michael.goette@helmholtz-berlin.de
      voila:
        short_description: A jupyter webapp container with voila opens voila
        description: A jupyter hub webapp container with voila installed.
        image: ghcr.io/nomad-hzb/perotf-image/jupyter:main
        path_prefix: voila/render
        with_path: true
        mount_path: /home/jovyan
        file_extensions:
          - ipynb
        maintainer:
          - name: Michael Götte
            email: michael.goette@helmholtz-berlin.de

meta:
  deployment: "oasis"
  deployment_url: "https://my-oasis.org/api"
  maintainer_email: "me@my-oasis.org"

logstash:
  enable: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1
